- Makefile
- @exequielrafaela - BBL-463 | updating makefile to push distributable to public PyPi leverage repo. - 6eb814f
> Feature/BBL-463 | pypi publish leverage

- Makefile
- @exequielrafaela - BBL-463 | updating makefile deps cmds - 3471a25
> BBL-463 | updating makefile deps cmds

- .gitignore
- LICENSE.txt
- leverage/__init__.py
- leverage/_parsing.py
- leverage/conf.py
- leverage/leverage.py
- leverage/logging.py
- leverage/path.py
- leverage/task.py
- setup.py
- General code refactoring
- Make the code more readable and easier to maintain
- Add relevant documentation whenever needed
> Leverage CLI Refactoring

- .gitignore
- conftest.py
- leverage/_parsing.py
- leverage/leverage.py
- tests/build_scripts/simple_build.py
- tests/conftest.py
- tests/test__parsing.py
- tests/test_conf.py
- tests/test_leverage.py
- tests/test_path.py
- First round of unit tests for Leverage
> Leverage CLI: unit tests

- .github/workflows/build-push-package.yml
- .github/workflows/build-push-test-package.yml
- Add a new workflow to test package publishing
- Use pipenv in actual publishing workflow to easy dependency management
> Add test workflow

- .github/workflows/build-push-package.yml
- .github/workflows/build-push-test-package.yml
- Dockerfile
- MANIFEST.in
- Pipfile
- Pipfile.lock
- README.md
- dev-requirements.txt
- leverage/tasks.py
- setup.cfg
- Drop support for python 3.6 and 3.7
- Fix setup.cfg
- Fix equals implementation for Tasks
> Fix workflows

- README.md
- dev-requirements.txt
- leverage/_internals.py
- leverage/leverage.py
- leverage/modules/credentials.py
- leverage/modules/project.py
- leverage/path.py
- tests/bats/leverage.bats
- tests/bats/utils.bash
Address points 1 and 3 from https://github.com/binbashar/le-tf-infra-aws/issues/47#issuecomment-891349471
> Feedback from third demo

- LICENSE.txt
* Replace MIT license with Apache 2.0
> Update License to Apache 2.0

- .github/workflows/build-push-package.yml
- leverage/__init__.py
* Bump version
* Run Slack hook unconditionally
> Fix version

- README.md
* Improve wording on README page
> Improve wording in README page

- .github/workflows/run-tests.yml
* Create a workflow to run unit test automatically for every PR
> Add workflow to automate unit tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
* Add github templates for issues and PRs
> Feature | Add github templates

- .github/workflows/run-tests.yml
- Makefile
- leverage/modules/credentials.py
- leverage/modules/project.py
- leverage/modules/terraform.py
- tests/bats/leverage.bats
- tests/bats/leverage_terraform.bats
- tests/bats/no_git_leverage.bats
- tests/bats/utils.bash
* Adopt new docker image to allow testing of features that make use of docker themselves
* Add integration tests for terraform
* Minor fixes
* Add a job for running integration tests
> Feature | Automate integration tests

- leverage/logger.py
- tests/test_logger.py
* Correct function that determines the log level configuration for the MFA script
* https://github.com/binbashar/le-tf-infra-aws-template/pull/16
* closes #62
> Fix | Configure correct log levels for MFA script

- leverage/modules/project.py
* Adapt project initialization and creation/rendering process to the updated template repository structure (template now is in its own directory)
* https://github.com/binbashar/le-tf-infra-aws-template/pull/17
* closes #44 since it is irrelevant now
> Feature | Update project initialization and creation

- .github/workflows/build-push-package.yml
* Fix `bump_version` step in release workflow
> Fix | Release Workflow

- leverage/container.py
- leverage/leverage.py
- leverage/modules/__init__.py
- leverage/modules/aws.py
- leverage/modules/terraform.py
- tests/bats/utils.bash
* Make a new `aws` module to handle AWS CLI commands independently and specially SSO related commands
* Make `terraform` module use the new container abstraction.
* #70
> Feature | AWS CLI SSO commands

- leverage/modules/aws.py
* Add safeguards in `aws configure sso` and `aws sso login` commands to gracefully fail when required values are missing.
> Enhancement | Add safeguards for missing values on SSO commands

- leverage/container.py
* Drop image tag default
* Simplify container errors Stack trace to only show last frame error message
> Enhancement | Drop image tag default

- leverage/container.py
- leverage/modules/terraform.py
* Add layer layout validation script like the one already implemented in leverage ref arch repo
* Call validation script upon `init`
Closes #30
> Feature | Add layer layout validation script

- leverage/modules/credentials.py
* Add a new `--fetch-mfa-device` flag in the `credentials configure` command.
* Relax some initially designed restrictions.
* To let the user determine when the tool should use a configured MFA device instead of relying in pre-baked behavior.
> Feature | Add --fetch-mfa-device flag instead of hardcoded behavior

- leverage/container.py
* Fix issue for terraform shell not launching
> Bug | Fix terraform shell environment launch

- leverage/modules/terraform.py
* Add a flag to skip layout validation entirely when initializing a layer.
> Feature | Add option to disable layout validation

- leverage/modules/credentials.py
* Create the required `build.env` file before configuring credentials in case its missing.
* If  `PROJECT` and `TERRAFORM_IMAGE_TAG` are not set in `build.env` the Docker container cannot run correctly.
> Fix | Create build.env before configuring credentials if necessary

- .github/workflows/release-management.yml
What?
action updated
Why?
testing to have it running
References
n/a
> 87 bug action updated

- .github/workflows/run-tests.yml
- Makefile
- leverage/container.py
- leverage/modules/aws.py
- leverage/modules/terraform.py
* "All Layers"feature added
TF base commands can be run as they are from inside a layer dir:
```
leverage tf init
```
...or with `--layers` option from the account dir:
```
leverage tf init --layers us-east-1/terraform-backend,global/sso
```
* the code inside `terraform.py` was refactored for sake of readability.
* Fulfill a user request
* Take advantage of the work and refactor code for clarity
n/a
> Issue 123 all layers option

- .github/workflows/build-push-package.yml
* Specifying Python version to setup-python action
* the workflow is failing due to version issue
n/a
> Set python version in setup-python action

- .github/workflows/run-tests.yml
- leverage/modules/terraform.py
* Removed passing-by-param the S3 Key
* It was introducing an error on multi layer inits. (as per the PR https://github.com/binbashar/leverage/issues/163)
* closes https://github.com/binbashar/leverage/issues/163
> ISSUE-163 Removed s3-key-by-parameter on init

- leverage/container.py
* Improve messages as per the Issues referenced below.
* Messages should be self-explanatories.
* closes https://github.com/binbashar/leverage/issues/167
* closes https://github.com/binbashar/leverage/issues/168
> ISSUE-168-167 Improving messages

- .github/workflows/build-push-package.yml
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`
> Fixed order to get last tag

- leverage/container.py
In response to: https://github.com/binbashar/leverage/pull/203#discussion_r1193927251
> [196] SSO login: feedback

- leverage/__init__.py
> Enhancement | updated to last version of toolbox

- README.md
* Add try-leverage in README section
* We are improving the developer experience with Leverage
> Update README adding try-leverage redirection

- leverage/container.py
* Whenever the SSO token expired message is displayed, also add a suggestion to run the login command to refresh credentials.
* Output reference screenshot:
* Closes #160
> Enhancement | Suggest login command when token expires

- leverage/container.py
- leverage/leverage.py
- leverage/modules/__init__.py
- leverage/modules/generic.py
- tests/test_containers/__init__.py
- tests/test_containers/test_leverage.py
Creates a generic command that spin up our base container so you can run things on it.
Additionally, it will let you mounts folders and files, and inject environment variables, in case you need to run extra software over it.
Because why not?!
closes #233
> [BB-233] Generic command

- .github/workflows/tests-unit-and-integration.yml
- .gitignore
- leverage/leverage.py
- leverage/modules/__init__.py
- setup.cfg
- tests/test_modules/test_credentials.py
* Adding unit tests for `_load_configs_for_credentials`
* Introducing [coveralls.io](https://coveralls.io/github/binbashar/leverage#step1), a way to track coverage over our tests.
* To reduce the probability of introducing bugs like https://github.com/binbashar/leverage/issues/242
https://github.com/binbashar/leverage/pull/232
> [BB-242] _load_configs_for_credentials test

- leverage/path.py
- tests/test_path.py
* Increase allowed depth for the search of the account directory, since some users may have a more deeply nested folder structure that previously expected.
* Closes 282
> feat: Increase account dir search depth
