setup.py

This should help when installing Leverage CLI on Python versions older than 3.8. For instance, 3.6 is the default Ubuntu 18.04.

Require an older version of yaenv in order to loosen up dependency constraints

---

.github/workflows/build-push-test-package.yml
leverage/modules/project.py

- Allow `build_push_test_package` to get the version to publish from user input. If no version to publish is provided then the latest published version is fetched form TestPypi and the next patch from that is used.
Allows for greater flexibility when it comes to quickly test published packages.

Get version for test publish from input

---

.github/workflows/run-tests.yml
Makefile
tests/bats/no_git_leverage.bats

* Modify Makefile to pull docker image from registry instead of building it when running tests
* Simplify unit testing workflow to reduce time consumption in actions
* Fix a bats test
* Closes #45

Feature | Pull docker image from registry for testing

---

leverage/modules/terraform.py

* Add the required mounted volumes and environment variables to the terraform container to be able to run MFA script when in shell.
* Pin terraform image tag to `1.0.9` as a safe default instead of `latest` as it previously was.
* Allow terraform output to take the MFA configuration from env file instead of it being always disabled
* Improve container entrypoint setting logic for MFA-enabled commands. Now these are only run in layer directories and never reach the MFA script when they are being execute elsewhere.
* closes #61 
* closes #60

Fix | `terraform` commands

---

leverage/conf.py
leverage/modules/credentials.py
leverage/modules/project.py

* AWS access keys files are now parsed as csv to extract the credentials
* Relative paths to `$HOME` are now allowed for providing access keys files locations
* Registering `security` credentials no longer errors out (the wrong set of credentials were being used for getting organization accounts)
* `project.yaml` and `build.env` files are no longer essential for the commands, a more complex logic to obtain the required information was implemented
* closes #58 
* closes #56 
* closes #55

Fix | `credentials` commands

---

leverage/modules/credentials.py
leverage/modules/terraform.py

* Change mounted volumes in terraform container as to avoid issues with AWS credentials when running MFA script
* Add defaults to values in credentials module that were causing issues when running in an uninitialized project

Fix | Mount AWS credentials correctly for Terraform commands

---

leverage/modules/terraform.py

* Stop mounting `$HOME/gitconfig` and `$HOME/.ssh/`
* These volumes are not necessary in the current iteration of the tool, if in the near future the need arises we should add them back in.

Patch | Remove unnecessary mounted volumes in container

---

.github/workflows/build-push-package.yml
leverage/__init__.py

* Use placeholder for `version` in `__init__.py` instead of keeping it updated.
* Version number is determined during packaging and tags are applied accordingly to the code. It's not necessary to keep an updated version of such number in the repository itself.
* It simplifies release process with no downside.

Patch | Use placeholder in version

---

leverage/modules/terraform.py

* Improve current directory checking for commands that require it by specifically considering the case of a command being launched from a configuration directory.
* Make MFA enabled shells to be opened only on layer level.
* Improve layer detection by considering a layer any directory containing `.tf` files. Project root, account root, and config directories are discarded early on by the first item of this list and it is assumed that region level directories do not contain any `.tf` files inside.

Fix | Allow terraform commands to run in nested layers

---

leverage/modules/credentials.py

* Updated accounts information obtained by the credential command will no longer be impacted via templates rendering. A more chirurgical approach will be used through the `hcledit` tool.
* This will preserve any already configured data instead of re writing the file to a state similar to its original one.

Enhancement | Prevent credentials command from overriding already configured values

---

leverage/modules/project.py

* Run a random harmless command before running `terraform fmt` just to ensure the docker image is already available.
* A status animation is shown during the formatting process. The same happens when the docker image is being pulled. If the image needs to be pulled at the moment of formatting the created project, then the cli attempts to show two status animations at the same time, which is not supported by rich.

Fix | Make sure image is pulled before formating

---

leverage/modules/terraform.py

* Make `.ssh` and `.gitconfig` directories available in the Leverage container.
* closes #79

Mount host `.ssh` and `.gitconfig` dirs in container

---

leverage/logger.py
leverage/modules/credentials.py
leverage/modules/project.py
leverage/modules/terraform.py
tests/test_logger.py

* Rename `get_mfa_script_log_level` to a more generic `get_script_log_level`
* Update `credentials` and `project` modules to use new container abstraction

Feature | Implement new container abstraction

---

leverage/container.py

* Prevent `terraform` and `aws` commands to run outside a Leverage project folder.
* The container handling process, the default mounting points to be precise, depend on configuration values that are defined in the Leverage project files. Some commands such as `terraform version` could be allowed to run outside this context, but the necessary extra logic to achieve this makes the investment not worth it.

Enhancement | Prevent containerized commands to run outside Leverage project context

---

leverage/modules/terraform.py

* Fix typo in `terraform destroy` that prevented command from running.

Fix | Typo in terraform destroy arguments

---

leverage/leverage.py
leverage/modules/aws.py

* Correctly handle subcommand name and flags resolution
* Reduce code duplication in `aws` command
* Hijacking some of the aws cli commands in order to support AWS SSO workflow requires some logic to find out which subcommand is being called. Current implementation allows for things like `aws sso configure` and `aws configure sso` to have the same effect, when only the first one should be correct. Also flags were incorrectly handled.
* Terraform uses single dash flags instead of posix double dashed ones which confuses click parameter parsing as explained in #89. Removing `-h` help option fixes this issue.
Fixes #89

Fix | Command parsing

---

leverage/modules/project.py

* Use `exec` instead of `start` when formatting code after creating a project.
* `start` launches the container as interactive, which conflicts with the animation displayed by rich when `dockerpty` hijacks the terminal, `exec` runs the operation in the background without interfering with the terminal.
* Addresses point 3 of #92

Fix | Fix error during project creation

---

leverage/container.py
leverage/modules/terraform.py

* Mount whole project instead of only the current layer.
* Load all `.tfvars` files found in global and account config directory when running a terraform command that requires it.
* Allows for greater flexibility when working in a project.
* Enables future planned features.
* Closes #90

Feature | Mount entire project and load multiple config files

---

.github/release-drafter.yml
.github/workflows/release-management.yml

* release-drafter files copied from https://github.com/binbashar/le-tf-infra-aws where they are working
* Here there were not working
n/a

ISSUE-87 Copied release drafter files from refarch

---

.github/workflows/build-push-test-package.yml
README.md
leverage/modules/credentials.py

* The `common.tfvars` file update was made to a wrong directory, fixed to the correct one
* Failure when `project.yaml` does not exist; fixed with the logic stated [here](https://github.com/binbashar/leverage/blob/0a78b7d8b0aad5f4d170822940bf79c2e451b072/leverage/modules/credentials.py#L234)
* The first item prevented the credentials from being updated in the common.tfvars files, causing the rest of the process to fail
* The second iten prevented the Leverage process from running when `project.yaml` file does not exist
n/a

114|115 bug accountid not updated, failure on missing project.yaml

---

leverage/modules/terraform.py

* Added option for bootstrap profile 
* at the moment of re init the terraform project, after creating the s3 bucket , the credentials are <short-name>-bootstrap , and will fail when checking it against the form used later, we need to consider this case scenario
* Closes #111 (https://github.com/binbashar/leverage/issues/111)

ISSUE-111 added option for bootstrap credentials

---

leverage/container.py

* add a meaningful message when missing docker image
* there is a need to communicate the error so the user can fix it
* Partially completes https://github.com/binbashar/leverage/issues/128

ISSUE-128 Pulling image step wrapped in a try-except block

---

leverage/__init__.py

* set specific toolbox version instead of latest
* to fix CLI to a specific version of Toolbox (this can be overwritten)
* https://github.com/binbashar/leverage/blob/fbcfeb10cf0b7ee16c343dbcd15a16bd2519d0c5/leverage/__init__.py#L7

ISSUE-139 Set specific toolbox version instead of latest

---

.github/workflows/run-tests.yml
Pipfile
README.md

The new Leverage CLI version >=1.8.0 uses a new image as background toolbox. Since the versioning for it is other than the old one, and if a project was firstly created with a Leverage CLI <1.8.0, the `build.env` file has to be changed.
Document this change.
How?
Old `build.env` version example:
```
PROJECT=bb
MFA_ENABLED=false
TERRAFORM_IMAGE_NAME=binbash/terraform-awscli-slim
TERRAFORM_IMAGE_TAG=1.1.9
```
New version example:
```
PROJECT=bb
MFA_ENABLED=false
TERRAFORM_IMAGE_TAG=1.2.7-0.0.5
```

ISSUE-146 docuented new build.env format

---

.github/workflows/build-push-test-package.yml
.github/workflows/run-tests.yml
Makefile
README.md
leverage/__init__.py
leverage/container.py
leverage/leverage.py
leverage/modules/__init__.py
leverage/modules/aws.py
leverage/modules/credentials.py
leverage/modules/terraform.py
leverage/modules/tfautomv.py

* S3 keys
* accept keys with region
* generate key when the key line in the tf file is missing (the s3 backend line has to be there anyway)
* accept more versions of the key to match refarch v1 and v2
* test-build workflow allows alpha and beta besides rc
*  toolbox version fixed to `__toolbox_version__ = "1.2.7-0.0.5"`
* added `region` var to the TF command line in TF container
* added logic to handle token file called `token`
* added properties to TF container class
* added TFAutomv container class
* added tfautomv command to Leverage CLI
* aws
* manage v1 and v2 main region (aka `region_primary` and `region`)
* added code for accounts and Org Units handle in Refarch v1 and v2
* credentials
* manage v1 and v2 main region (aka `region_primary` and `region`)
* terraform
* init: pass …

Issue 141 s3 key multi region support

---

.github/PULL_REQUEST_TEMPLATE.md

* adding Dod-CCP reference to PR template
* In order to have a checklist of tasks to be done before every release
n/a

ISSUE-153 added Dod-CCP reference to PR template

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

- [Adding 1st version of the binbash Leverage standard CODE-OF-CONDUNCT.md and CONTRIBUTING.md](https://github.com/binbashar/leverage/commit/196399186ebd583ba05297b18e4cba3eaf9586b7)  - @[exequielrafaela](https://github.com/binbashar/leverage/commits?author=exequielrafaela)
Necessary and in line to the following issues:
- https://github.com/binbashar/le-ref-architecture-doc/issues/150
- https://github.com/binbashar/le-ref-architecture-doc/issues/143

Doc | Adding CODE-OF-CONDUNCT.md and CONTRIBUTING.md

---

leverage/container.py
leverage/modules/terraform.py

* The way the `.ssh` dir is mounted into the container was changed from
* mount ~/.ssh -> ~/.ssh
* to:
* mount ~/.ssh -> /tmp/.ssh
* cp -r /tmp/.ssh ~/
* chown to container user and chmod to 600
* If the `.ssh` files are owned by other than the current container user, or the config file has permissions other than `600` the `bad owner permissions issue` is got.
* solves https://github.com/binbashar/leverage/issues/173
* Review the checklist [here](https://binbash.atlassian.net/l/cp/BthxSQ0j)

ISSUE-173 Changed way to add .ssh dir to get rid of bad owner permissions

---

setup.cfg

A fix for a bug introduced in https://github.com/binbashar/leverage/pull/172
```
>> leverage --version
Traceback (most recent call last):
File "/usr/local/bin/leverage", line 5, in <module>
from leverage import leverage
File "/home/frivera/.local/lib/python3.10/site-packages/leverage/__init__.py", line 18, in <module>
from leverage.leverage import leverage
File "/home/frivera/.local/lib/python3.10/site-packages/leverage/leverage.py", line 11, in <module>
from leverage.modules import aws
File "/home/frivera/.local/lib/python3.10/site-packages/leverage/modules/__init__.py", line 7, in <module>
from .kubectl import kubectl
File "/home/frivera/.local/lib/python3.10/site-packages/leverage/modules/kubectl.py", line 4, in <module>
from leverage.containers.kubectl import KubeCtlContainer …
```

the package is missing the containers module

---

leverage/container.py
tests/test_containers/test_terraform.py

If you are using the `TF_PLUGIN_CACHE_DIR` terraform feature, then translate it into the container.
To avoid repeatedly download the same tf providers over all the layers.
https://github.com/binbashar/leverage/issues/179
They way terraform works is by creating symlinks from the `.terraform/providers` folder into the `TF_PLUGIN_CACHE_DIR` folder. So to keep symlinks working once outside leverage, we need to mount the directory structure as it is in the host filesystem.

Terraform provider cache support

---

README.md
leverage/__init__.py
leverage/modules/project.py

* Add SSO layer to provision the landing zone with that by default.
* The Landing Zone now uses SSO by default.
TBD

Add SSO layer to provision the landing zone with that by default

---

leverage/_utils.py
leverage/container.py
leverage/containers/kubectl.py
tests/test_containers/test_kubectl.py

While trying https://github.com/binbashar/leverage/pull/172 with an MFA account, I found out that it wasn't working.
The command was not able to find credentials while trying to run commands inside the container. 
I was because of the `.aws` folder been ephemeral during the run of the commands.
So you have to call the MFA logic everytime you need to run AWS related commands.
```
[12:45:11.610] INFO     Fetching  AWS credentials...                                                                                                                                   
[15:45:11]   INFO	MFA: Found 2 profile/s
[15:45:11]   INFO	MFA: Attempting to get temporary credentials for profile cdot-apps-devstg-devops
[15:45:13]   INFO	MFA: Using cached credentials
[15:45:15]   INFO	MFA: Credentials written …
```

[126] Kubectl: remove unnecessary shenanigans for MFA

---

leverage/container.py
tests/test_containers/test_aws.py

Print the SSO login url as fallback.
In case the `webbrowser` lib fails to open the browser.
`closes #196`

[196] SSO login: fallback link

---

.github/workflows/release-pypi-build-push-test-package.yml
README.md

We decided to push the pre-releases version of Leverage directly to the [official Package Index](https://pypi.org/) (instead of the [testing one](https://test.pypi.org/)).
Because they support pre-releases versions (you have to use the `--pre` flag on pip). So it doesn't make any sense to use 2 different package indexes.

[205] Push pre-releases builds to the official pypi

---

leverage/containers/kubectl.py
leverage/modules/kubectl.py
tests/test_containers/test_kubectl.py

Force regular commands to be run on a layer, to avoid issues while refreshing aws credentials.
For a better UX.
Reported by @juanmatias while trying to run a `kc` command on a non-layer folder of a project.

kubectl commands must be run from a layer too

---

.github/workflows/tests-unit-and-integration.yml
leverage/modules/project.py
tests/test_modules/test_project.py

Add validations for the project long name (coming from project.yaml).
That name is used for folders and other stuff, that has character limitations.
* closes #212

[BB-212] Project name validation

---

leverage/container.py
leverage/modules/terraform.py
tests/test_containers/__init__.py
tests/test_containers/test_terraform.py

Create a command dedicated to refresh the AWS credentials, relying on the `terraform` sso/mfa scripts
To simplify the credentials renewal on any script

refresh-credentials command

---

leverage/container.py
leverage/leverage.py
leverage/modules/__init__.py
leverage/modules/shell.py
leverage/modules/terraform.py
leverage/modules/utils.py

Rename `generic` command to `shell` for better association.
Fix mount/env-vars support on the `terraform` commands.
#233

[BB-233] Rename generic to shell + fix terraform mount/env-var support

---

leverage/modules/credentials.py

Problem has been explained in the issue [HERE](https://github.com/binbashar/leverage/issues/242).
* It is a small fix after recently merged [PR](https://github.com/binbashar/leverage/pull/232).
* CLI breaks on running `leverage credentials configure --type BOOTSTRAP`
* https://github.com/binbashar/leverage/issues/242

fix: 'AWSCLIContainer' object has no attribute 'common_conf

---

.github/release-drafter.yml

* Add Version Compatibility section as a footer of the release.
* We decided to add such section so that Leverage users can know which Docker Toolbox Image they can use with every release.
* #158 

Add Version Compatibility section to release notes

---

leverage/modules/project.py
tests/test_modules/test_project.py

Validate the short project name length at project creation time.
Otherwise it breaks the flow, no the credential generation steps.
closes #235
https://github.com/binbashar/le-tf-infra-aws-template/blob/ab1f86db606f24581825910b969a456bc408aa6a/le-resources/project.yaml#L2

[BB-235] project short name validation

---

leverage/modules/aws.py

Given the changes introduced in the SSO role management, these restrictions are not required anymore.

[SSO Login] Remove now unnecessary restrictions

---

leverage/modules/credentials.py
leverage/modules/project.py
leverage/path.py
tests/test_path.py
tests/test_root_path.py

* When trying to access the `root` variable and and exception happened, root cannot be accessed because it does not exist.
* We have to use else there so we only try to access `root` when there is no exception happening.
* New get_project_root_or_current_dir_path method to get the root of the project path. 
* To avoid issues when running  `leverage --version`. Otherwise the command would just exit with an unhandled exception like it is described in the issue.
* Use `closes #229`

[229] Fix issue with --version option

---

.github/workflows/tests-integration.yaml
leverage/modules/terraform.py
tests/test_modules/terraform/test_handle_apply_arguments_parsing.py

* Current logic for parsing arguments after `apply` does not work as expected.
* `leverage tf apply -target kubernetes_manifest.irfq` -> fails
* `leverage tf apply -target kubernetes_manifest.irfq` -> works
* both options for specifying parameters with space or equal should work.
* https://github.com/binbashar/leverage/issues/159
* `closes #159`

[159] Improve apply arguments parsing logic

---

.github/workflows/release-pypi-build-push-test-package.yml
Makefile

* Detect Operating system and use GNU sed & sort commands.
* Current bump version commands in Makefile only works in MacOS.

Fix portability issues with sed and sort in MacOS & Linux

---

poetry.lock
pyproject.toml

We are facing this issue in some of our CI tests: https://github.com/docker/docker-py/issues/3256
And it is probably affecting people already.
The issue is fixed in docker-py [7.1.0](https://github.com/docker/docker-py/releases/tag/7.1.0) but that would mean a major upgrade in our core library.
Let's go for the quick fix by now

Pin requests to 2.31

---

.github/workflows/tests-integration.yaml
.github/workflows/tests-unit.yml
tests/test_containers/test_kubectl.py
tests/test_containers/test_terraform.py
tests/test_modules/test_credentials.py

* Adding python 3.12 to integration and unit test workflows
* Make sure that we test against the newest python version

feat: Add python 3.12 to test workflows

---

leverage/container.py

* Make Leverage more compatible with Podman to allow the use of this container manager as an alternative to Docker.
* Closes 283

feat: Increase compatibiliy with podman

---

.github/workflows/tests-integration.yaml
Dockerfile
leverage/container.py
leverage/path.py
tests/bats/leverage.bats

Make sure there is always a .gitconfig file present in the home directory.
So git can work properly inside the container.
`closes #267`

[BV-267] Make sure .gitconfig is always present
